// WARNING: DO NOT DELETE THIS FILE
// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).

const WitnetParserLib = artifacts.require("WitnetParserLib");
const WitnetProxy = artifacts.require("WitnetProxy");
//const SocialMonitor = artifacts.require("SocialMonitor");
const TwitterAuth = artifacts.require("TwitterAuth");
const TwitterPointCounter = artifacts.require("TwitterPointCounter");

module.exports = async function (deployer) {
  //await deployer.link(WitnetParserLib, [SocialMonitor, TwitterAuth, TwitterPointCounter]);
  //await deployer.deploy(SocialMonitor, WitnetProxy.address);
  await deployer.link(WitnetParserLib, [TwitterAuth, TwitterPointCounter]);
  await deployer.deploy(TwitterAuth, WitnetProxy.address);
  await deployer.deploy(
    TwitterPointCounter,
    WitnetProxy.address,
    TwitterAuth.address,
    "1435205856832983041",
    100000000000000000n
  );
};
